const links = {
  header: [
    { id: 0, title: 'JS',      to: '/js' },
    { id: 1, title: 'Webpack', to: '/wp' },
    { id: 2, title: 'React',   to: '/react' },
    { id: 3, title: 'Redux',   to: '/redux' },
    { id: 4, title: 'NodeJS',  to: '/nodejs' },
  ],

  js: [
    { id: 0,  title: 'Class',         to: '/js/class' },
    { id: 1,  title: 'Class II',      to: '/js/class2' },
    { id: 2,  title: 'Object',        to: '/js/object' },
    { id: 3,  title: 'Object II',     to: '/js/object2' },
    { id: 4,  title: 'Function',      to: '/js/function' },
    { id: 5,  title: 'Function II',   to: '/js/function2' },
    { id: 6,  title: 'Array',         to: '/js/array' },
    { id: 7,  title: 'Server',        to: '/js/server' },
    { id: 8,  title: 'Import/Export', to: '/js/export', divider: true },
    { id: 9,  title: 'DOM',           to: '/js/dom' },
    { id: 10, title: 'Events',        to: '/js/events' },
    { id: 11, title: 'Forms',         to: '/js/forms' },
    { id: 12, title: 'Storage',       to: '/js/storage' },
    { id: 13, title: 'Script',        to: '/js/script' },
    { id: 14, title: 'Methods',       to: '/js/methods'},
    { id: 15, title: 'Var/Let/Const', to: '/js/vars', divider: true },
    { id: 16, title: 'Types',         to: '/js/types' },
    { id: 17, title: 'String',        to: '/js/string' },
    { id: 18, title: 'Number',        to: '/js/mumber' },
    { id: 19, title: 'Boolean',       to: '/js/boolean' },
    { id: 20, title: 'Null & Un-ed',  to: '/js/null' },
    { id: 21, title: 'Math(+ / -)',   to: '/js/math' },
    { id: 22, title: 'Logic',         to: '/js/logic' },
    { id: 23, title: 'Cycles',        to: '/js/cycles' },
  ],

  webpack: [
    { id: 0,  title: 'Install',   to: '/wp/install' },
    { id: 1,  title: 'Config',    to: '/wp/config' },
    { id: 2,  title: 'JS-Babel',  to: '/wp/js' },
    { id: 3,  title: 'CSS',       to: '/wp/css' },
    { id: 4,  title: 'HTML',      to: '/wp/html' },
    { id: 5,  title: 'Images',    to: '/wp/img' },
    { id: 6,  title: 'Fonts',     to: '/wp/fonts' },
    { id: 7,  title: 'Markdown',  to: '/wp/md' },
    { id: 8,  title: 'Plugins',   to: '/wp/plugins' },
    { id: 9,  title: 'ESLint',    to: '/wp/eslint' },
    { id: 10, title: 'Editor',    to: '/wp/editor' },
    { id: 11, title: 'Structure', to: '/wp/structure' },
  ],

  react: [
    { id: 0,  title: 'Template',     to: '/react/template' },
    { id: 1,  title: 'Components',   to: '/react/components' },
    { id: 2,  title: 'JSX',          to: '/react/jsx' },
    { id: 3,  title: 'State',        to: '/react/state' },
    { id: 4,  title: 'Props',        to: '/react/props' },
    { id: 5,  title: 'PropTypes',    to: '/react/proptypes' },
    { id: 6,  title: 'Styling',      to: '/react/styling' },
    { id: 7,  title: 'Images',       to: '/react/images' },
    { id: 8,  title: 'Output Data',  to: '/react/output-data' },
    { id: 9,  title: 'Maping Data',  to: '/react/maping-data' },
    { id: 10, title: 'Routing',      to: '/react/routing' },
    { id: 11, title: 'Switcher',     to: '/react/switcher' },
    { id: 12, title: 'Transitions',  to: '/react/transitions' },
    { id: 13, title: 'Refs X',       to: '/react/refs' },
    { id: 14, title: 'Forms',        to: '/react/forms' },
    { id: 15, title: 'Lifecycle',    to: '/react/lifecycle' },
    { id: 16, title: 'Events',       to: '/react/events' },
    { id: 17, title: 'Fetch in CBB', to: '/react/fetch' },
    { id: 18, title: 'Server API X', to: '/react/server' },
    { id: 19, title: 'Redux X',      to: '/react/redux' },
    { id: 20, title: 'Plugins X',    to: '/react/plugins' },
    { id: 21, title: 'GatsbyJS',     to: '/react/gatsby-js' },
  ],

  redux: [
    { id: 0, title: 'Install', to: '/redux/install' },
  ],

  nodejs: [
    { id: 0, title: 'Install',      to: '/nodejs/install' },
    { id: 1, title: 'Npm / Yarn',   to: '/nodejs/npm-yarn' },
    { id: 2, title: 'Package.json', to: '/nodejs/package-json' },
    { id: 3, title: 'Browser-sync', to: '/nodejs/browser-sync' },
    { id: 4, title: 'Express',      to: '/nodejs/express' },
  ]
};

export default links;
